### ISSUE TITLE
Publish to homebrew?

### ISSUE THREAD

**Issue by bcomnes** [mattly/bork#55]
Would you be interested in getting this added to homebrew?  Either through the official taps, or a custom tap? 

(Fantastic work btw! Love it!)

**Comment by frdmn** [comment]
Hi @bcomnes. I started to work on exactly this earlier today, but right now it's impossible because bork doesn't like to be executed as symlink (which homebrew does during the installation of packages). 

This is why I submitted issue #54 which aims to fix that problem. Once that's done, we can submit the homebrew Formula to the official [repository](https://github.com/Homebrew/homebrew) :)

**Comment by bcomnes** [comment]
Missed that.  Closing in favor of #54

**Comment by frdmn** [comment]
@bcomnes bork is now available via brew:

```
❯  ~  brew info bork
bork: stable 0.9.1
Bash DSL for config management
https://github.com/mattly/bork
/usr/local/Cellar/bork/0.9.1 (95 files, 104.6K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/bork.rb
```

**Comment by bcomnes** [comment]
@frdmn you da :bomb: 

Thanks! :)

**Comment by frdmn** [comment]
@bcomnes You're very welcome! :blush:
